title: Ali Grant
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9147134160157293
  brandStrength: 1
  lightness: 0.04337275121361017
  brandColors:
    - '#050505'
    - '#FFFFE3'
    - '#263636'
    - '#7C8F9D'
    - '#636557'
  rhythmicContrast: 0.1136755633633584
typography_spectrum: 0.5382192661054432
description: On a voyage of discovery
layout_spectrum: 0.1630824
name: aligrant
